apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "snapshotter.fullname" . }}-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "snapshotter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "snapshotter.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io