{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "snapshotter.role" . }}
  labels:
    {{- include "snapshotter.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.rbac.rules }}
rules:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}